### ISSUE TITLE
Reference Files for the given example VCF

### ISSUE THREAD

**Issue by ALogandha** [ambj/MuPeXI#40]
Hi,

I am trying to run MuPeXi on the given example VCF (https://raw.githubusercontent.com/ambj/MuPeXI/master/data/example.vcf) using the below command but end up with error:

`MuPeXI.py -v data/example.vcf -a HLA-A01:01,HLA-A02:02`

I am using `homo_sapiens_refseq_vep_104_GRCh38.tar.gz` for VEP cache (`http://ftp.ensembl.org/pub/release-104/variation/indexed_vep_cache/homo_sapiens_vep_104_GRCh38.tar.gz`) and fasta files downloaded from `http://ftp.ensembl.org/pub/release-95/fasta/homo_sapiens` as the reference.

Please find the error message pasted below:

> Reading in data
>         Creating proteome reference dictionary
> Traceback (most recent call last):
>   File "MuPeXI/MuPeXI.py", line 1800, in <module>
>     main(sys.argv[1:])
>   File "MuPeXI/MuPeXI.py", line 44, in main
>     proteome_reference, sequence_count = build_proteome_reference(paths.proteome_ref_file, input_.webserver, species)
>   File "MuPeXI/MuPeXI.py", line 280, in build_proteome_reference
>     proteome_reference[geneID][transID] += line.strip()
> UnboundLocalError: local variable 'geneID' referenced before assignment

Could I request you to confirm I am using the correct references to run the example VCF? 

I appreciate your help!

Thanks in advance.

Regards,
Ashmitaa.

**Comment by zyxNo1** [comment]
I have the same question. Any idea?
