### ISSUE TITLE
AssertionError: Allele "HLA-B*07:02" not stated in NetMHCpan output

### ISSUE THREAD

**Issue by mimifp** [ambj/MuPeXI#43]
I'm trying to run MuPeXI pipeline with test data. There seems to be a problem with NetMHCpan, but I can't seem to fix it. I have checked the paths requested by the tool in its installation, as well as the MuPeXI `config.ini` file.  I have also changed the permissions to the `$NETMHCpan/data/version file`, giving write and read permissions for other users. Moreover, I hace also added `netmhcpan` executable to my user $PATH.

I am working with a conda eviroment to be able to use Python 2.7 and the required versions of pandas, numpy, vep and biopython, since I am running on an HPC with Slurm as task manager. The NetMHCpan-4.0 tool is out of this enviroment, but works separately.

The `data/allelenames` file does contain the allele HLA-B07:02 it says it cannot find.

Any idea what might be happening?
Thanks in advance

```bash
(mupexi) [uscmgmfp@login209-18 data]$ ../MuPeXI.py -v example.vcf -c /mnt/lustre/scratch/nlsas/home/usc/mg/translational_oncology/1_tools/24_mupexi/MuPeXI/config.ini -e example_expression.tsv -a HLA-A*01:01,HLA-A*11:01,HLA-B*07:02,HLA-B*35:01 -t

Reading in data
	Creating expression file dictionary
	Creating proteome reference dictionary
	Creating genome reference dictionary
	Creating cancer genes list

VEP: Starting process for running the Ensembl Variant Effect Predictor
	Detecting variant caller
		MuTect2
	Change VCF to the VEP compatible
	Extracting allele frequencies
	Running VEP
	Creating mutation information dictionary

MuPeX: Starting mutant peptide extraction
	Extracting all possible peptides from reference
		Peptides of 9 aa are being extracted
	Peptide extraction begun
		Running 9 aa normal peptide match

MuPeI: Starting mutant peptide informer
	Writing temporary peptide file
	Running NetMHCpan eluted ligand prediction
Unable to open(r) file $NETMHCpan/data/version
	Creating NetMHCpan eluted ligand prediction file dictionary
	Writing output file
Traceback (most recent call last):
  File "../MuPeXI.py", line 1800, in <module>
    main(sys.argv[1:])
  File "../MuPeXI.py", line 101, in main
    output_file = write_output_file(peptide_info, expression, net_mhc_BA, net_mhc_EL, unique_alleles, cancer_genes, tmp_dir, input_.webserver, input_.print_mismatch, allele_fractions, input_.expression_type, transcript_info, reference_peptides, proteome_reference, protein_positions, version)
  File "../MuPeXI.py", line 1261, in write_output_file
    assert hla in net_mhc_EL, 'Allele "{}" not stated in NetMHCpan output'.format(hla)
AssertionError: Allele "HLA-B*07:02" not stated in NetMHCpan output
```

**Comment by levinyi** [comment]
I encountered a similar issue and resolved it by ensuring the netMHCpan configuration was correctly set up. Please check the following in your configuration:

1. Verify the correct path to the netMHCpan home directory. It should look like this in your configuration file:
`setenv NMHOME /path/to/netMHC/netMHCpan-4.0/`

2. Ensure the path to the temporary directory (TMPDIR) is correctly specified. You might want to create a 'tmp' folder in your netMHCpan installation directory for this purpose:
`setenv TMPDIR /path/to/netMHCpan-4.0/tmp/`

3. Check the netMHCpan path in the MuPeXI's config file. It should be specified like this:
`MHC = /path/to/netMHCpan-4.0/netMHCpan`

Make sure these paths are accurate and reflect your actual directory structure.
