### ISSUE TITLE
UnboundLocalError: local variable 'geneID' referenced before assignment

### ISSUE THREAD

**Issue by zyxNo1** [ambj/MuPeXI#44]
I'm trying to run MuPeXI pipeline with test data, but there is something wrong and I can't fix it.  
The command line is:
`./MuPeXI.py -v ./data/example.vcf -e data/example_expression.tsv -a HLA-A01:01,HLA-B08:01`

Then I got:
_Reading in data
        Creating expression file dictionary
        Creating proteome reference dictionary
Traceback (most recent call last):
  File "./MuPeXI.py", line 1800, in <module>
    main(sys.argv[1:])
  File "./MuPeXI.py", line 44, in main
    proteome_reference, sequence_count = build_proteome_reference(paths.proteome_ref_file, input_.webserver, species)
  File "./MuPeXI.py", line 280, in build_proteome_reference
    proteome_reference[geneID][transID] += line.strip()
UnboundLocalError: local variable 'geneID' referenced before assignment_

How can I solve this?
Thanks in advance.

**Comment by zyxNo1** [comment]
Resolved. Just decompress cdna and pep files.
